### ISSUE TITLE
Roadmap Modified Quasichemical

### ISSUE THREAD

**Issue by doomphoenix-qxz** [doomphoenix-qxz/MoltenSaltThermodynamics.jl#1]
TODO:

- [ ] Reproduce all figures from Pelton and Blander, "Modified Quasichemical Method I--Binary Solutions"
- [ ] Once the above "unofficial test suite" works properly, create an official test suite
- [ ] Refactor MQCM into its own repository named "ModifiedQuasichemical.jl"
- [ ] Refactor to use other packages such as ThermoState.jl and PhysProps.jl where possible
- [ ] Begin work on multicomponent systems
- [ ] Optimization to generate MQCM parameters from experimental data for binary systems
